version: '3.3'

services:

  # !! IMPORTANT !!
  # This image should only be used in development
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  app:
    image: node:lts
    container_name: web
    volumes:
      - ./:/var/www/app
    links:
      - redis
    ports:
      - 8000:8000
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=8000
    command:
      sh -c 'cd /var/www/app && yarn && yarn build && yarn internal:dev'

volumes:
  portainer_data:
